"""Add multi-tenancy support with Organization, Farm, Plantation, and Buyer models

Revision ID: 54ae7b9fa3a4
Revises: 
Create Date: 2025-11-24 02:26:15.609936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ae7b9fa3a4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_code'), 'organizations', ['code'], unique=True)
    op.create_table('buyers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('payment_terms', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyers_organization_id'), 'buyers', ['organization_id'], unique=False)
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('total_area_hectares', sa.Float(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_organization_id'), 'farms', ['organization_id'], unique=False)
    op.create_table('plantations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('area_hectares', sa.Float(), nullable=True),
    sa.Column('tree_count', sa.Integer(), nullable=True),
    sa.Column('planting_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plantations_code'), 'plantations', ['code'], unique=True)
    op.create_index(op.f('ix_plantations_farm_id'), 'plantations', ['farm_id'], unique=False)
    op.add_column('harvests', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.add_column('harvests', sa.Column('plantation_id', sa.Integer(), nullable=False))
    op.add_column('harvests', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('harvests', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('harvests', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_harvests_organization_id'), 'harvests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_harvests_plantation_id'), 'harvests', ['plantation_id'], unique=False)
    op.create_foreign_key(None, 'harvests', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'harvests', 'plantations', ['plantation_id'], ['id'])
    op.create_foreign_key(None, 'harvests', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'harvests', 'organizations', ['organization_id'], ['id'])
    op.drop_column('harvests', 'plantation')
    op.add_column('milling', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.add_column('milling', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('milling', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('milling', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_milling_organization_id'), 'milling', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'milling', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'milling', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'milling', 'organizations', ['organization_id'], ['id'])
    op.add_column('sales', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.add_column('sales', sa.Column('buyer_id', sa.Integer(), nullable=False))
    op.add_column('sales', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_sales_buyer_id'), 'sales', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_sales_organization_id'), 'sales', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'sales', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'sales', 'buyers', ['buyer_id'], ['id'])
    op.create_foreign_key(None, 'sales', 'users', ['created_by'], ['id'])
    op.drop_column('sales', 'buyer_name')
    op.add_column('storage', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.add_column('storage', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('storage', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('storage', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_storage_organization_id'), 'storage', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'storage', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'storage', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'storage', 'organizations', ['organization_id'], ['id'])
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_column('users', 'organization_id')
    op.drop_constraint(None, 'storage', type_='foreignkey')
    op.drop_constraint(None, 'storage', type_='foreignkey')
    op.drop_constraint(None, 'storage', type_='foreignkey')
    op.drop_index(op.f('ix_storage_organization_id'), table_name='storage')
    op.drop_column('storage', 'updated_at')
    op.drop_column('storage', 'updated_by')
    op.drop_column('storage', 'created_by')
    op.drop_column('storage', 'organization_id')
    op.add_column('sales', sa.Column('buyer_name', sa.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_organization_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_buyer_id'), table_name='sales')
    op.drop_column('sales', 'updated_at')
    op.drop_column('sales', 'updated_by')
    op.drop_column('sales', 'created_by')
    op.drop_column('sales', 'buyer_id')
    op.drop_column('sales', 'organization_id')
    op.drop_constraint(None, 'milling', type_='foreignkey')
    op.drop_constraint(None, 'milling', type_='foreignkey')
    op.drop_constraint(None, 'milling', type_='foreignkey')
    op.drop_index(op.f('ix_milling_organization_id'), table_name='milling')
    op.drop_column('milling', 'updated_at')
    op.drop_column('milling', 'updated_by')
    op.drop_column('milling', 'created_by')
    op.drop_column('milling', 'organization_id')
    op.add_column('harvests', sa.Column('plantation', sa.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'harvests', type_='foreignkey')
    op.drop_constraint(None, 'harvests', type_='foreignkey')
    op.drop_constraint(None, 'harvests', type_='foreignkey')
    op.drop_constraint(None, 'harvests', type_='foreignkey')
    op.drop_index(op.f('ix_harvests_plantation_id'), table_name='harvests')
    op.drop_index(op.f('ix_harvests_organization_id'), table_name='harvests')
    op.drop_column('harvests', 'updated_at')
    op.drop_column('harvests', 'updated_by')
    op.drop_column('harvests', 'created_by')
    op.drop_column('harvests', 'plantation_id')
    op.drop_column('harvests', 'organization_id')
    op.drop_index(op.f('ix_plantations_farm_id'), table_name='plantations')
    op.drop_index(op.f('ix_plantations_code'), table_name='plantations')
    op.drop_table('plantations')
    op.drop_index(op.f('ix_farms_organization_id'), table_name='farms')
    op.drop_table('farms')
    op.drop_index(op.f('ix_buyers_organization_id'), table_name='buyers')
    op.drop_table('buyers')
    op.drop_index(op.f('ix_organizations_code'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
